from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query

from app.ai.pipelines.audit_pipeline import (
    get_audit_pipeline,
)


router = APIRouter(
    prefix="/audit",
    tags=["AI Audit"],
)


# =========================================================
# AUDIT ONE CTDISR CONTROL
# =========================================================

@router.post(
    "/controls/{control_id}",
)
def audit_control(
    control_id: str,
    top_k: int = Query(
        5,
        ge=1,
        le=20,
        description="Number of evidence chunks retrieved per document type.",
    ),
    max_new_tokens: int = Query(
        400,
        ge=50,
        le=1000,
        description="Maximum number of tokens generated by Llama.",
    ),
):
    """
    Run AI audit for ONE CTDISR control.

    Example:

        POST /api/v1/audit/controls/4.1

    The pipeline will:

        1. Load control 4.1
        2. Retrieve evidence
        3. Build RAG context
        4. Run fine-tuned Llama
        5. Return PTA response
        6. Return recommendation
        7. Return action owner
    """

    pipeline = get_audit_pipeline()

    try:

        result = pipeline.audit_control(
            control_id=control_id,
            top_k=top_k,
            max_new_tokens=max_new_tokens,
        )

        return {
            "success": True,
            "message": (
                f"AI audit completed for "
                f"CTDISR control '{control_id}'."
            ),
            "result": result,
        }

    except ValueError as exc:

        raise HTTPException(
            status_code=404,
            detail=str(exc),
        )

    except FileNotFoundError as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=(
                "AI audit failed: "
                f"{str(exc)}"
            ),
        )